### ISSUE TITLE
Tests chained together

### ISSUE THREAD

**Issue by nicktimko** [celeen/PythonDataStructures#1]
I wasn't sure, but Nose apparently runs tests in the order they appear in the file, so if everything is OK they'll all run fine, but if anything fails early it will cascade and cause everything else to fail/error.

**Comment by celeen** [comment]
Thanks, Nick!

For now, I've added numbers to the test names. It turns out Nose runs things in the order they appear in the file-- unless the test class inherits from unittest, in which case they run in alphabetical order.

I added a quickfix for this that adds test numbers to each test name, but I'll keep my eyes open to see if I can find a more elegant solution.

Also, I'm not too concerned about having 14 failed tests at the outset; it's supposed to be that way. The student will build out methods and features according to failures, and the tests will start to pass as more of the main class gets written.
